export type QuestionKind = "code" | "short-text" | "multiple-choice";

export type AssessmentQuestion = {
  id: string;
  section: string;
  number: string;
  prompt: string;
  marks: number;
  kind: QuestionKind;
  instructions?: string[];
  options?: string[];
  placeholder?: string;
};

export const assessmentMeta = {
  title: "Educare Tech Hub Cohort Re-Entry CBT",
  durationMinutes: 180,
  totalMarks: 100,
  audience: "All students in the cohort",
  scope: "CS50 Weeks 0 to 5 + bootcamp content up to before React",
};

export const questions: AssessmentQuestion[] = [
  {
    id: "practical-1",
    section: "Section A: Practical Projects",
    number: "1",
    marks: 10,
    kind: "code",
    prompt: "Student Result Analyzer",
    instructions: [
      "Build a program in JavaScript that works with an array of student objects such as `{ id, name, score }`.",
      "Print all student names.",
      "Return only students who passed with score >= 50.",
      "Calculate the class average.",
      "Find the top student.",
      "Display the result in the browser DOM.",
    ],
    placeholder: "Write your JavaScript solution here...",
  },
  {
    id: "practical-2",
    section: "Section A: Practical Projects",
    number: "2",
    marks: 10,
    kind: "code",
    prompt: "Search Efficiency Demo",
    instructions: [
      "Create a small program in C or JavaScript that searches for a target value in a sorted list.",
      "Implement linear search.",
      "Implement binary search.",
      "Print whether the item was found.",
      "Print the number of steps used by each method.",
      "Briefly state why one search is faster on sorted data.",
    ],
    placeholder: "Write your C or JavaScript solution here...",
  },
  {
    id: "practical-3",
    section: "Section A: Practical Projects",
    number: "3",
    marks: 10,
    kind: "code",
    prompt: "Balanced Brackets Checker",
    instructions: [
      "Write a program in C or JavaScript that checks whether a string of brackets is valid.",
      "Use a stack approach.",
      "Handle (), {}, and [].",
      "Return true or false.",
      "Include at least 3 test cases.",
    ],
    placeholder: "Write your stack-based solution here...",
  },
  {
    id: "practical-4",
    section: "Section A: Practical Projects",
    number: "4",
    marks: 10,
    kind: "code",
    prompt: "Vanilla JS Mini SPA",
    instructions: [
      "Build a simple browser app with two views: Home and Dashboard or Profile.",
      "Use no full page reload.",
      "Render UI from a state object.",
      "Include one interactive feature such as theme toggle, task counter, or profile card update.",
    ],
    placeholder: "Describe and write your HTML/CSS/JS implementation here...",
  },
  {
    id: "practical-5",
    section: "Section A: Practical Projects",
    number: "5",
    marks: 10,
    kind: "code",
    prompt: "Async Data Dashboard",
    instructions: [
      "Build a small JavaScript app that loads data asynchronously from a local JSON file or mocked promise.",
      "Show a loading state.",
      "Handle errors with try/catch.",
      "Compute at least 3 insights such as total orders, average amount, count by status, or top 3 highest values.",
      "Display results clearly.",
    ],
    placeholder: "Write your async dashboard solution here...",
  },
  {
    id: "fill-1",
    section: "Section B: Fill-In-The-Gap",
    number: "6",
    marks: 5,
    kind: "short-text",
    prompt: "In C, the function commonly used to print output to the screen is ________.",
    placeholder: "Type your answer...",
  },
  {
    id: "fill-2",
    section: "Section B: Fill-In-The-Gap",
    number: "7",
    marks: 5,
    kind: "short-text",
    prompt: "In JavaScript, the array method used to return a new array containing only elements that match a condition is ________.",
    placeholder: "Type your answer...",
  },
  {
    id: "fill-3",
    section: "Section B: Fill-In-The-Gap",
    number: "8",
    marks: 5,
    kind: "short-text",
    prompt: "A function that calls itself is known as ________.",
    placeholder: "Type your answer...",
  },
  {
    id: "mcq-1",
    section: "Section C: Multiple-Choice Questions",
    number: "9",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which number system uses only 0 and 1?",
    options: ["Decimal", "Binary", "Octal", "Hexadecimal"],
  },
  {
    id: "mcq-2",
    section: "Section C: Multiple-Choice Questions",
    number: "10",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which of the following best defines an algorithm?",
    options: [
      "A type of browser",
      "A step-by-step method for solving a problem",
      "A CSS layout system",
      "A database table",
    ],
  },
  {
    id: "mcq-3",
    section: "Section C: Multiple-Choice Questions",
    number: "11",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which data structure follows Last In, First Out?",
    options: ["Queue", "Stack", "Tree", "Hash table"],
  },
  {
    id: "mcq-4",
    section: "Section C: Multiple-Choice Questions",
    number: "12",
    marks: 2,
    kind: "multiple-choice",
    prompt: "In C, which symbol is used to declare or dereference a pointer?",
    options: ["&", "*", "%", "#"],
  },
  {
    id: "mcq-5",
    section: "Section C: Multiple-Choice Questions",
    number: "13",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which search algorithm is generally faster on a sorted array?",
    options: ["Linear search", "Recursive scan", "Binary search", "Sequential search"],
  },
  {
    id: "mcq-6",
    section: "Section C: Multiple-Choice Questions",
    number: "14",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which JavaScript method combines array values into one final result?",
    options: ["map()", "filter()", "reduce()", "find()"],
  },
  {
    id: "mcq-7",
    section: "Section C: Multiple-Choice Questions",
    number: "15",
    marks: 2,
    kind: "multiple-choice",
    prompt: "What does DOM stand for?",
    options: [
      "Document Object Model",
      "Data Object Method",
      "Display Oriented Model",
      "Dynamic Output Mode",
    ],
  },
  {
    id: "mcq-8",
    section: "Section C: Multiple-Choice Questions",
    number: "16",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which keyword must be used to define a function that can use await?",
    options: ["promise", "defer", "async", "yield"],
  },
  {
    id: "mcq-9",
    section: "Section C: Multiple-Choice Questions",
    number: "17",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Why is a base case important in recursion?",
    options: [
      "It makes the program compile faster",
      "It stops the recursion from running forever",
      "It converts recursion to iteration",
      "It sorts the output automatically",
    ],
  },
  {
    id: "mcq-10",
    section: "Section C: Multiple-Choice Questions",
    number: "18",
    marks: 2,
    kind: "multiple-choice",
    prompt: "Which of the following best describes a hash table?",
    options: [
      "A structure for fast key-value lookup",
      "A type of nested loop",
      "A method for styling tables in CSS",
      "A sorting-only structure",
    ],
  },
  {
    id: "short-1",
    section: "Section D: Short Answer Questions",
    number: "19",
    marks: 3,
    kind: "short-text",
    prompt: "What is the difference between RAM and permanent storage?",
    placeholder: "Write a brief answer...",
  },
  {
    id: "short-2",
    section: "Section D: Short Answer Questions",
    number: "20",
    marks: 3,
    kind: "short-text",
    prompt: "Why does binary search require sorted data?",
    placeholder: "Write a brief answer...",
  },
  {
    id: "short-3",
    section: "Section D: Short Answer Questions",
    number: "21",
    marks: 3,
    kind: "short-text",
    prompt: "What is the difference between == and === in JavaScript?",
    placeholder: "Write a brief answer...",
  },
  {
    id: "short-4",
    section: "Section D: Short Answer Questions",
    number: "22",
    marks: 3,
    kind: "short-text",
    prompt: "Explain the difference between a stack and a queue.",
    placeholder: "Write a brief answer...",
  },
  {
    id: "short-5",
    section: "Section D: Short Answer Questions",
    number: "23",
    marks: 3,
    kind: "short-text",
    prompt: "In a single-page application, why do we avoid full page reloads when switching views?",
    placeholder: "Write a brief answer...",
  },
];

export const questionsById = new Map(questions.map((question) => [question.id, question]));
